[options]
addons_path = /mnt/extra-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$dY5xrpVyrnXuvZeSUqrVeg$HOgvzl.wo5A3HlkdS7r4Fsk00nLa43dCdIM/lGdvTFWsq4Melj1bkfWkQGqLhjDCPXBsDX6.OA7plY0i/ZUM5g

